import voice from "./voice-timeline.json";

// Word timings of public/audio/voz-cuenta.wav (seconds), generated by
// scripts/build_timeline.py from the TTS alignment after trimming pauses.
export const WORDS: { text: string; start: number; end: number }[] = voice.words;
export const VOICE_DURATION: number = voice.duration;

const w = (i: number) => WORDS[i].start;

export const CUE = {
  menos: w(0),
  mas: w(2),
  tuPlan: w(4),
  activo: w(7),
  compruebalo: w(8),
  sin: w(11),
  soporte: w(14),
  anticipate: w(15),
  renovacion: w(18),
  fecha: w(22),
  proximo: w(25),
  revisa: w(27),
  contratado: w(30),
  rfc: w(31),
  cfdi: w(32),
  modulos: w(35),
  todoClaro: w(37),
  cuenta: w(42),
  conoce: w(43),
  url: w(47),
};
