import voice from "./voice-timeline.json";

// Word timings of public/audio/voz.wav (seconds), generated by
// scripts/build_timeline.py from the TTS alignment after trimming pauses.
export const WORDS: { text: string; start: number; end: number }[] = voice.words;
export const VOICE_DURATION: number = voice.duration;

// Start time of word #i (index into WORDS).
export const w = (i: number) => WORDS[i].start;
export const wEnd = (i: number) => WORDS[i].end;

// Named cues used by the scenes (indices into WORDS).
export const CUE = {
  llego: w(3),
  contratar: w(8),
  gestionar: w(10),
  personaliza: w(13),
  aLaMedida: w(14),
  operacionEnd: wEnd(19),
  cfdi: w(22),
  rfc: w(23),
  modulos: w(25),
  colaboradores: w(27),
  integraciones: w(29),
  elige: w(32),
  mensual: w(35),
  anual: w(37),
  y: w(38),
  veinte: w(40),
  alElegir: w(41),
  masFlex: w(44),
  masControl: w(46),
  masFispal: w(48),
  conoce: w(50),
  experiencia: w(53),
  url: w(55),
};
